/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.vadosity.resume.tailor;

import static org.junit.jupiter.api.Assertions.assertTrue;

import java.util.ArrayList;
import java.util.List;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

import org.junit.jupiter.api.Test;

class SentenceUtilTest {
	
//    @Test void containsAllWordsInOrderReturnsTrue() {
//    	
//    	String source="Now is the time";
//    	List<String> words = Arrays.asList("Now","is","the","time");
//        assertTrue(SentenceUtil.containsAllWordsInOrder(source, words), "SentenceUtil.containsAllWordsInOrder should return 'true'");
//    }
	
	@Test void verifyBracketRegex()
    {
    	String sentence = "[Bracket] Let's find the brackets [with some text] and remove it with [other] brackets. [#hashtag]";
    	String regex="\\[(.*?)\\]";
    	
    	Pattern pattern = Pattern.compile(regex);
    	
    	Matcher matcher = pattern.matcher(sentence);
    	matcher.find();
    	List<String> matchingStrings = new ArrayList<>();
    	
    	int start=0;
    	int end=-1;
    	
    	while ( matcher.find(start)) {
    		start = matcher.start();
    		end = matcher.end();
    		matchingStrings.add(sentence.substring(start, end)); 
    		start=end;
    	}
    	
    	assertTrue(matchingStrings.contains("[with some text]"));
    	assertTrue(matchingStrings.contains("[#hashtag]"));
    	assertTrue(matchingStrings.contains("[Bracket]"));
    	assertTrue(matchingStrings.contains("[other]"));
    }
}
