/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.vadosity.resume.tailor;

import static org.junit.jupiter.api.Assertions.assertTrue;

import java.util.Set;

import org.junit.jupiter.api.Test;

class TrimBulletsRequestTest {
	
	@Test void verifyCsvWithQuotesRegex()
    {
		String regex = TrimBulletsRequest.CSV_WITH_QUOTES_REGEX;
		String sentence="a,b,\"C, is separate\",d";
		String[] sa = sentence.split(regex);
		assertTrue(sa[0].equals("a"),"sa[0] should be 'a'");
		assertTrue(sa[1].equals("b"),"sa[1] should be 'b'");
		assertTrue(sa[2].equals("\"C, is separate\""),"sa[2] should be '\"C, is separate\"'");
		assertTrue(sa[3].equals("d"),"sa[3] should be 'd'");
    }
	
	@Test void convertToCsvSetTest()
	{
		String csv="a ,";
		Set<String> set = TrimBulletsRequest.convertToCsvSet(csv);
		assertTrue ( set.size()==1);
		assertTrue ( set.toArray()[0].equals("a"));
		
		csv="a ,, B";
		set = TrimBulletsRequest.convertToCsvSet(csv);
		assertTrue ( set.size()==2);
		assertTrue ( set.toArray()[1].equals("B"));
		
		csv="a,b,\"C, is separate\",d";
		set = TrimBulletsRequest.convertToCsvSet(csv);
		assertTrue ( set.size()==4);
		assertTrue ( set.contains("\"C, is separate\""));
		
	}
}
